package(default_visibility = ["//visibility:public"])

java_binary(
    name = "main",
    srcs = ["Main.java"],
    main_class = "q1.Main",
    deps = [":gcd"],
)

java_library(
    name = "gcd",
    srcs = ["Gcd.java"],
)
